language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
script:
  - yarn test
  - yarn build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: master
